<title>CAD-AMS</title>
<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
<link href="<?=base_url('css/styles.css')?>" rel="stylesheet" type="text/css" />
<link href="<?=base_url('css/bootstrap.min.css')?>" rel="stylesheet" type="text/css" />
<link href="<?=base_url('css/chosen.min.css')?>" rel="stylesheet" type="text/css" />